name: CodSpeed

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash -e -l {0}

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: namespace-profile-sparrow-compilation-linux-next;container.privileged=true;container.host-pid-namespace=true
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Install GCC
        id: install_cc
        uses: rlalik/setup-cpp-compiler@v2
        with:
          compiler: gcc-16

      - name: Checkout
        uses: actions/checkout@v7

      - name: Configure benchmark build
        run: |
          cmake -B build \
                -G Ninja \
                -DCMAKE_BUILD_TYPE=RelWithDebInfo \
                -DSPARROW_COMPUTE_ENABLE_CODSPEED=ON \
                -DSPARROW_COMPUTE_CODSPEED_MODE=simulation \
                -DBUILD_BENCHMARKS=ON \
                -DFETCH_DEPENDENCIES_WITH_CMAKE=ON

      - name: Build benchmark target
        run: cmake --build build --target sparrow-compute_bench

      - name: Run CodSpeed benchmarks
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: ./build/sparrow-compute_bench
